version: '3'

services:
    postgres_db:
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5431:5432
            
volumes:
    postgres_data: